### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by inoue0426** [weiba/MOFGCN#1]
Hi,

I want to run this code on a Linux machine.
But, not sure how to run this code. 

If I run the entire_main.py, I get the error about the import_path.
Not sure what this is though. Is this library? I can't find this library on PyPI

```python
$ python CCLE/MOFGCN/Entire_Drug_Cell/entire_main.py 
Traceback (most recent call last):
  File "CCLE/MOFGCN/Entire_Drug_Cell/entire_main.py", line 5, in <module>
    from import_path import *
ModuleNotFoundError: No module named 'import_path'
```

And if I commented out, I got this error.

```python
 $ python CCLE/MOFGCN/Entire_Drug_Cell/entire_main.py 
Traceback (most recent call last):
  File "CCLE/MOFGCN/Entire_Drug_Cell/entire_main.py", line 6, in <module>
    from MOFGCN.model import GModel
```

I don't know how to resolve this. Could you give me more instructions about this?

**Comment by weiba** [comment]
Dear Yoshitaka Inoue：

  Thanks for sending us message about the code running error. Please refer
to the attachment for the answers. Hopefully, it can answer your question.
Don't hesitate contact us if you have any questions or concerns.

Best regards,
Wei Peng

Yoshitaka Inoue ***@***.***> 于2022年10月8日周六 07:02写道：

**Comment by weiba** [comment]
1. ModuleNotFoundError: No module named 'import_path'
Delete this sentence directly and import dir_path from MOFGCN.myutils as follows:
 
from MOFGCN.myutils import roc_auc, translate_result, dir_path

2. from MOFGCN.model import GModel

This error is caused by path incorrect. MOFGCN.model is under the directory of CCLE or GDSC. So if you run the program under Windows and Pycharm, you can mark the directory CCLE or GDSC as "sources root".

If you run the code under Linux, you can add the following two sentences at the first line of the code file.

import sys
sys.path.append("../..")

**Comment by inoue0426** [comment]
@weiba 
It worked! Thank you for your help!
